### PR TITLE
reformat cpp code

### PR DESCRIPTION
**Pull request by jundizhou**
Signed-off-by: jundizhou <jundizhou@harmonycloud.cn>

### CODE REVIEW

**Comment by sanyangji** [comment]
Can you declare the code style specification , so that all developers can follow to make the code style consistent.

**Comment by dxsup** [comment]
I think he reformatted the code utilizing CLion's "Reformat Code" tool. We can export its default code style to [.clang-format](https://www.jetbrains.com/help/clion/clangformat-as-alternative-formatter.html) and store it under the root directory  of `/probe`.

**Review by sanyangji — APPROVED** [review]
I apply the format and get the same result.
LGTM

**Comment by sanyangji** [comment]
@dxsup Any more advice?

**Comment by dxsup** [comment]
Do you guys feel comfortable with indenting "two spaces" at a time? If so, then LGTM.

**Comment by sanyangji** [comment]
> Do you guys feel comfortable with indenting "two spaces" at a time? If so, then LGTM.

Actually not, 4 spaces may be better for me.

**Comment by dxsup** [comment]
@jundizhou @yaofighting @hocktea214 How do you think?

**Comment by dxsup** [comment]
We decide to use the original Google C++ Style.

**Pull request merged**
